<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.0" />
    <PackageReference Include="StreamJsonRpc" Version="2.24.84" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TombLib.Scripting.Lua\TombLib.Scripting.Lua.csproj" />
    <ProjectReference Include="..\TombLib.Scripting\TombLib.Scripting.csproj" />
  </ItemGroup>

</Project>
