<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\search-16.png" />
    <None Remove="Resources\TE.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TombLib\TombLib.Forms\TombLib.Forms.csproj" />
    <ProjectReference Include="..\DarkUI.WPF\DarkUI.WPF.csproj" />
    <ProjectReference Include="..\DarkUI\DarkUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CustomTabControl">
      <HintPath>..\..\Libs\CustomTabControl.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\search-16.png" />
    <Resource Include="Resources\TE.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="OriginalComparison.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
