//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TombIDE.ScriptEditor.Resources.Syntaxes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustSyntaxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustSyntaxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TombIDE.ScriptEditor.Resources.Syntaxes.CustSyntaxes", typeof(CustSyntaxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_ADD_DEATH_ANIMATION, SlotOfCreature, AnimNumber.
        /// </summary>
        public static string CUST_ADD_DEATH_ANIMATION {
            get {
                return ResourceManager.GetString("CUST_ADD_DEATH_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_AMMO, SlotOfAmmo, Ammo flags (AMMO_...), Damage, ShotsForBox, ShotsWithWeapon, Extra, IdTriggerGroupWhenHitEnemy, DamageForExplosion, Speed, Gravity, IdAddEffectToAmmo, IdTriggerGroupAtEnd.
        /// </summary>
        public static string CUST_AMMO {
            get {
                return ResourceManager.GetString("CUST_AMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_BACKGROUND, BackGroundType (BKGDT_...), Flags (BKGDF_...), Parameter, ImageId.
        /// </summary>
        public static string CUST_BACKGROUND {
            get {
                return ResourceManager.GetString("CUST_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_BAR, BarType (BAR_...), FlagsBar (FBAR_...), XOrigin, YOrigin, XSize, YSize, IdColor1, IdColor2, Extra.
        /// </summary>
        public static string CUST_BAR {
            get {
                return ResourceManager.GetString("CUST_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_BIKE_VS_ENEMIES, Slot+(HIT_...) flag array.
        /// </summary>
        public static string CUST_BIKE_VS_ENEMIES {
            get {
                return ResourceManager.GetString("CUST_BIKE_VS_ENEMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_BINOCULARS, FLAGS (BINF_...), Parameter, CompassImage, CompassRectAndFlags, SextantImage, SextantRectAndFlags, LightnessRectAndFlags, ZoomRectAndFlags, LightSwitchRectAndFlags, FontID.
        /// </summary>
        public static string CUST_BINOCULARS {
            get {
                return ResourceManager.GetString("CUST_BINOCULARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_CAMERA, Flags (FCAM_...), DistanceChaseCam, VOrientChaseCam, HOrientChaseCam, DistanceCombatCam, VOrientCombatCam, DistanceLookCam, HeightLookCam, SpeedCamera.
        /// </summary>
        public static string CUST_CAMERA {
            get {
                return ResourceManager.GetString("CUST_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_CD_SINGLE_PLAYBACK, CdMode value (CDM_...).
        /// </summary>
        public static string CUST_CD_SINGLE_PLAYBACK {
            get {
                return ResourceManager.GetString("CUST_CD_SINGLE_PLAYBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_DARTS, IdCustDarts, Dart Flags (DRT_...), IdAddEffect, Speed, EmittingTimer, PrimaryColorIDRgb, SecondaryColorIDRgb, IdTriggerGroup.
        /// </summary>
        public static string CUST_DARTS {
            get {
                return ResourceManager.GetString("CUST_DARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_DISABLE_FORCING_ANIM_96.
        /// </summary>
        public static string CUST_DISABLE_FORCING_ANIM_96 {
            get {
                return ResourceManager.GetString("CUST_DISABLE_FORCING_ANIM_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Syntax for this command was not specified by its creator.
        /// </summary>
        public static string CUST_DISABLE_MISSING_SOUNDS {
            get {
                return ResourceManager.GetString("CUST_DISABLE_MISSING_SOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_DISABLE_MISSING_SOUNDS.
        /// </summary>
        public static string CUST_DISABLE_PUSH_AWAY_ANIMATION {
            get {
                return ResourceManager.GetString("CUST_DISABLE_PUSH_AWAY_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_DISABLE_SCREAMING_HEAD.
        /// </summary>
        public static string CUST_DISABLE_SCREAMING_HEAD {
            get {
                return ResourceManager.GetString("CUST_DISABLE_SCREAMING_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_ESCAPE_FLY_CAMERA, ENABLED / DISABLED, KeyBoardScanCode.
        /// </summary>
        public static string CUST_ESCAPE_FLY_CAMERA {
            get {
                return ResourceManager.GetString("CUST_ESCAPE_FLY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_FIX_BUGS, BugsToFix flags (BUGF_...).
        /// </summary>
        public static string CUST_FIX_BUGS {
            get {
                return ResourceManager.GetString("CUST_FIX_BUGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_FIX_WATER_FOG_BUG, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_FIX_WATER_FOG_BUG {
            get {
                return ResourceManager.GetString("CUST_FIX_WATER_FOG_BUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_FLARE, Flags for Flare (FFL_...), SecondsOfLifeTime, Red, Green, Blue, Intensity.
        /// </summary>
        public static string CUST_FLARE {
            get {
                return ResourceManager.GetString("CUST_FLARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_FMV_CUTSCENE, Flags (FMV_...).
        /// </summary>
        public static string CUST_FMV_CUTSCENE {
            get {
                return ResourceManager.GetString("CUST_FMV_CUTSCENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_HAIR_TYPE, HairType  (HAIR_...).
        /// </summary>
        public static string CUST_HAIR_TYPE {
            get {
                return ResourceManager.GetString("CUST_HAIR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_HARPOON, HarpoonFlags (HRP_...), TopBorder, DistanceFromCam, Orient_X, Orient_Y, Orient_Z, HarpoonSpeed, HarpoonGravity.
        /// </summary>
        public static string CUST_HARPOON {
            get {
                return ResourceManager.GetString("CUST_HARPOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_INNER_SCREENSHOT, QualityScreenshotFlags (QSF_...).
        /// </summary>
        public static string CUST_INNER_SCREENSHOT {
            get {
                return ResourceManager.GetString("CUST_INNER_SCREENSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_KEEP_DEAD_ENEMIES, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_KEEP_DEAD_ENEMIES {
            get {
                return ResourceManager.GetString("CUST_KEEP_DEAD_ENEMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_KEEP_LARA_HP, TargetLevel.
        /// </summary>
        public static string CUST_KEEP_LARA_HP {
            get {
                return ResourceManager.GetString("CUST_KEEP_LARA_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_LIGHT_OBJECT 34, SlotLight, Red, Green, Blue, Intensity, Time ; Not sure what the author meant with that 34... Probably useless?.
        /// </summary>
        public static string CUST_LIGHT_OBJECT {
            get {
                return ResourceManager.GetString("CUST_LIGHT_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_LOOK_TRASPARENT, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_LOOK_TRASPARENT {
            get {
                return ResourceManager.GetString("CUST_LOOK_TRASPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_NEW_SOUND_ENGINE, NewSoundEngine flags (NSE_...), SoundExtension (SEXT_...), LongFadeOut, ShortFadeOut.
        /// </summary>
        public static string CUST_NEW_SOUND_ENGINE {
            get {
                return ResourceManager.GetString("CUST_NEW_SOUND_ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_NO_TIME_IN_SAVELIST, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_NO_TIME_IN_SAVELIST {
            get {
                return ResourceManager.GetString("CUST_NO_TIME_IN_SAVELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_PARALLEL_BARS, FlagsParallelBar (PB_...), SpeedForSlide, MaxTurns.
        /// </summary>
        public static string CUST_PARALLEL_BARS {
            get {
                return ResourceManager.GetString("CUST_PARALLEL_BARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_PAUSE_FLY_CAMERA, ENABLED / DISABLED, KeyBoardScanCode.
        /// </summary>
        public static string CUST_PAUSE_FLY_CAMERA {
            get {
                return ResourceManager.GetString("CUST_PAUSE_FLY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_RAIN, FlagsForRain (FR_...), DropSize, SprinklerAmount, MaxRain, MinRain, Float1, Float4, Float8, Float16, Extra.
        /// </summary>
        public static string CUST_RAIN {
            get {
                return ResourceManager.GetString("CUST_RAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_ROLLING_BOAT, SlotBoat, FlagsRollingBoats (FRB_...), SwingingSpeed, PitchingSpeed, RollingSFX.
        /// </summary>
        public static string CUST_ROLLING_BOAT {
            get {
                return ResourceManager.GetString("CUST_ROLLING_BOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_ROLLINGBALL_PUSHING, Distance, PushAnim, FailedAnim, FrameOfMoving, FrameOfActivation, FramesOfInvulnerability, Speed.
        /// </summary>
        public static string CUST_ROLLINGBALL_PUSHING {
            get {
                return ResourceManager.GetString("CUST_ROLLINGBALL_PUSHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SAVE_LOCUST, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_SAVE_LOCUST {
            get {
                return ResourceManager.GetString("CUST_SAVE_LOCUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SCREENSHOT_CAPTURE, SecondsOfDurate, FrameGap, QualityScreenshotFlag (QSF_...).
        /// </summary>
        public static string CUST_SCREENSHOT_CAPTURE {
            get {
                return ResourceManager.GetString("CUST_SCREENSHOT_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_CREDITS_LEVEL, NumberOfEndLevel.
        /// </summary>
        public static string CUST_SET_CREDITS_LEVEL {
            get {
                return ResourceManager.GetString("CUST_SET_CREDITS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_INV_ITEM, SlotOfItem.
        /// </summary>
        public static string CUST_SET_INV_ITEM {
            get {
                return ResourceManager.GetString("CUST_SET_INV_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_JEEP_KEY_SLOT, SlotForJeepKey.
        /// </summary>
        public static string CUST_SET_JEEP_KEY_SLOT {
            get {
                return ResourceManager.GetString("CUST_SET_JEEP_KEY_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_OLD_CD_TRIGGER, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_SET_OLD_CD_TRIGGER {
            get {
                return ResourceManager.GetString("CUST_SET_OLD_CD_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_SECRET_NUMBER, NumberOfSecrets.
        /// </summary>
        public static string CUST_SET_SECRET_NUMBER {
            get {
                return ResourceManager.GetString("CUST_SET_SECRET_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_STATIC_DAMAGE, Damage, PoisonIntensity.
        /// </summary>
        public static string CUST_SET_STATIC_DAMAGE {
            get {
                return ResourceManager.GetString("CUST_SET_STATIC_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_STILL_COLLISION, Collision Flags (COLL_...), LowerHeight, MoveableArray.
        /// </summary>
        public static string CUST_SET_STILL_COLLISION {
            get {
                return ResourceManager.GetString("CUST_SET_STILL_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SET_TEXT_COLOR, Text Type (TT_...), Color for Text (CL_...).
        /// </summary>
        public static string CUST_SET_TEXT_COLOR {
            get {
                return ResourceManager.GetString("CUST_SET_TEXT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SFX, TypeSound (TS_...), Sound Effect Number.
        /// </summary>
        public static string CUST_SFX {
            get {
                return ResourceManager.GetString("CUST_SFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SHATTER_RANGE, FirstStaticAsShatter, LastStaticAsShatter.
        /// </summary>
        public static string CUST_SHATTER_RANGE {
            get {
                return ResourceManager.GetString("CUST_SHATTER_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SHATTER_SPECIFIC, Slot1, Slot2, Slot3, SlotN.
        /// </summary>
        public static string CUST_SHATTER_SPECIFIC {
            get {
                return ResourceManager.GetString("CUST_SHATTER_SPECIFIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SHOW_AMMO_COUNTER, Color, FormatFlags (FT_...) , BlinkTime, SizeCharacter (SC_...), ShowCounterFlags (SHOWC_...).
        /// </summary>
        public static string CUST_SHOW_AMMO_COUNTER {
            get {
                return ResourceManager.GetString("CUST_SHOW_AMMO_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SLOT_FLAGS, Slot, FlagsForSlot (FFS_...).
        /// </summary>
        public static string CUST_SLOT_FLAGS {
            get {
                return ResourceManager.GetString("CUST_SLOT_FLAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_SPEED_MOVING, Speed.
        /// </summary>
        public static string CUST_SPEED_MOVING {
            get {
                return ResourceManager.GetString("CUST_SPEED_MOVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_STATIC_TRANSPARENCY, GlassOpacity, IceOpacity.
        /// </summary>
        public static string CUST_STATIC_TRANSPARENCY {
            get {
                return ResourceManager.GetString("CUST_STATIC_TRANSPARENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_TEXT_ON_FLY_SCREEN, ENABLED / DISABLED.
        /// </summary>
        public static string CUST_TEXT_ON_FLY_SCREEN {
            get {
                return ResourceManager.GetString("CUST_TEXT_ON_FLY_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_TITLE_FMV, FmvNumber, TestMultiPlay.
        /// </summary>
        public static string CUST_TITLE_FMV {
            get {
                return ResourceManager.GetString("CUST_TITLE_FMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_TR5_UNDERWATER_COLLISIONS.
        /// </summary>
        public static string CUST_TR5_UNDERWATER_COLLISIONS {
            get {
                return ResourceManager.GetString("CUST_TR5_UNDERWATER_COLLISIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_WATERFALL_SPEED, PixelScroll.
        /// </summary>
        public static string CUST_WATERFALL_SPEED {
            get {
                return ResourceManager.GetString("CUST_WATERFALL_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Customize= CUST_WEAPON, SlotOfWeapon, Weapon flags (WEAP_...) , SoundForShot, FramesForRecharge, DurateFlash, Extra, MaxDistanceForAiming, FrameToTakeWeapon, FrameToLetWeapon, Random, VPositionOfWeapon, Unknown, FrameCounter, FrameMinRange, FrameMaxRange, OrigX, OrigY, OrigZ, OrigOrient.
        /// </summary>
        public static string CUST_WEAPON {
            get {
                return ResourceManager.GetString("CUST_WEAPON", resourceCulture);
            }
        }
    }
}
