//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TombIDE.ScriptEditor.Resources.Syntaxes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParamSyntaxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParamSyntaxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TombIDE.ScriptEditor.Resources.Syntaxes.ParamSyntaxes", typeof(ParamSyntaxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_ACTOR_SPEECH, SpeechId, SpeechFlags (SPCF_...), Parameter, FrameRate, SpeechSlot, HeadSlotMesh, FirstMeshIndex, SpeechMeshAmount, CommandArray.
        /// </summary>
        public static string PARAM_ACTOR_SPEECH {
            get {
                return ResourceManager.GetString("PARAM_ACTOR_SPEECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_BIG_NUMBERS, Many Numbers separeted by commas.
        /// </summary>
        public static string PARAM_BIG_NUMBERS {
            get {
                return ResourceManager.GetString("PARAM_BIG_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_CIRCLE, IdParamList, xCenter, yCenter, Radius.
        /// </summary>
        public static string PARAM_CIRCLE {
            get {
                return ResourceManager.GetString("PARAM_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_COLOR_ITEM, IdParamList, ColorType (COLTYPE_...), ItemIndex, Index1ColorRGB, Index2ColorRGB, SpeedChange.
        /// </summary>
        public static string PARAM_COLOR_ITEM {
            get {
                return ResourceManager.GetString("PARAM_COLOR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_INPUT_BOX, InputBoxId, BckImageId, WFontId, MaxChars, SfxSound, Flags (RIB_...), ExtraParam.
        /// </summary>
        public static string PARAM_INPUT_BOX {
            get {
                return ResourceManager.GetString("PARAM_INPUT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_LIGHTNING, IdParamList, Lightning flags (LGTN_...), SourcePosItem, TargetPosItem, IdColorRGB, Intensity, SoundEffect, Size, ParticleDurate, IntervalTime, Alfa, Beta.
        /// </summary>
        public static string PARAM_LIGHTNING {
            get {
                return ResourceManager.GetString("PARAM_LIGHTNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_MOVE_ITEM, IdParamList, Flags (FMOV_...), IndexItem, Direction (DIR_...), Distance, Speed, MovingSound, FinalSound, Extra.
        /// </summary>
        public static string PARAM_MOVE_ITEM {
            get {
                return ResourceManager.GetString("PARAM_MOVE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_PRINT_TEXT, IdPrintText, Color (CL_...), FontType (FT_...), BlinkTime, DurateTime, X_Position, Y_Position.
        /// </summary>
        public static string PARAM_PRINT_TEXT {
            get {
                return ResourceManager.GetString("PARAM_PRINT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_QUADRILATERAL, IdParamList, Xa, Ya, Xb, Yb, Xc, Yc, Xd, Yd.
        /// </summary>
        public static string PARAM_QUADRILATERAL {
            get {
                return ResourceManager.GetString("PARAM_QUADRILATERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_RECT, RectId, XOrigin, YOrigin, Width, Height, ForeColor, BackColor.
        /// </summary>
        public static string PARAM_RECT {
            get {
                return ResourceManager.GetString("PARAM_RECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_ROTATE_ITEM, IdParamList, FlagsRotation (FROT_...), ItemIndex, DirHRotation (ROTH_...), HRotationAngle, SpeedHRotation, DirVRotation (ROTV_...), VRotationAngle, SpeedVRotation, MovingSound, FinalSound.
        /// </summary>
        public static string PARAM_ROTATE_ITEM {
            get {
                return ResourceManager.GetString("PARAM_ROTATE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_SCALE_ITEM, IdScaling, ItemIndex, Flags Scaling (FSCA_...), BeginSizePercentage, FinalSizePercentage, PercentageSpeed.
        /// </summary>
        public static string PARAM_SCALE_ITEM {
            get {
                return ResourceManager.GetString("PARAM_SCALE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_SET_CAMERA, IdSetCamera, Flags (FSCAM_...), DistanceCam, VOrientCam, HOrientCam, SpeedCamera.
        /// </summary>
        public static string PARAM_SET_CAMERA {
            get {
                return ResourceManager.GetString("PARAM_SET_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_SHOW_SPRITE, IdParamShowSprite, Flags Show Sprites (FSS_...), OriginX, OriginY, Width, Height, SlotSprite, SpriteIndex, IdColorRGB, GridX, GridY, Extra Value.
        /// </summary>
        public static string PARAM_SHOW_SPRITE {
            get {
                return ResourceManager.GetString("PARAM_SHOW_SPRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_SWAP_ANIMATIONS, ASwapId, SourceFirstAnim, TargetFirstAnim, NumberOfAnimations.
        /// </summary>
        public static string PARAM_SWAP_ANIMATIONS {
            get {
                return ResourceManager.GetString("PARAM_SWAP_ANIMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_TRIANGLE, IdParamList, Xa, Ya, Xb, Yb, Xc, Yc.
        /// </summary>
        public static string PARAM_TRIANGLE {
            get {
                return ResourceManager.GetString("PARAM_TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Parameters= PARAM_WTEXT, IdParameter, Flags (WTF_...), WindowsFontId, TimeDurate, Left, Top, Right, Bottom.
        /// </summary>
        public static string PARAM_WTEXT {
            get {
                return ResourceManager.GetString("PARAM_WTEXT", resourceCulture);
            }
        }
    }
}
