<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MdXaml" Version="1.27.0" />
    <PackageReference Include="TextMateSharp" Version="2.0.3" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DarkUI\DarkUI.WPF\DarkUI.WPF.csproj" />
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
    <ProjectReference Include="..\TombLib\TombLib.csproj" />
    <ProjectReference Include="..\TombLib.Forms\TombLib.Forms.csproj" />
    <ProjectReference Include="..\TombLib.Scripting.Core\TombLib.Scripting.Core.csproj" />
    <ProjectReference Include="..\TombLib.WPF\TombLib.WPF.csproj" />
  </ItemGroup>
</Project>