<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net8.0-windows</TargetFramework>
    <LangVersion Condition="'$(LangVersion)' == ''">12</LangVersion>
    <Configurations Condition="'$(Configurations)' == ''">Debug;Release</Configurations>
    <Platforms Condition="'$(Platforms)' == ''">x64;x86</Platforms>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'Any CPU' or '$(Platform)' == 'AnyCPU'">x64</Platform>
    <NormalizedPlatform>$(Platform.Replace(' ', ''))</NormalizedPlatform>
    <NormalizedPlatform Condition="'$(NormalizedPlatform)' == ''">x64</NormalizedPlatform>
    <UseSharedOutputPath Condition="'$(UseSharedOutputPath)' == ''
        and '$(MSBuildProjectName)' != 'DarkUI.WPF.Demo'
        and '$(MSBuildProjectName)' != 'Example'
        and '$(MSBuildProjectName.EndsWith(`.Tests`))' != 'True'">true</UseSharedOutputPath>
    <SharedDebugOutputRoot Condition="'$(SharedDebugOutputRoot)' == '' and '$(UseSharedOutputPath)' == 'true'">Build</SharedDebugOutputRoot>
    <SharedReleaseOutputRoot Condition="'$(SharedReleaseOutputRoot)' == '' and '$(UseSharedOutputPath)' == 'true'">BuildRelease</SharedReleaseOutputRoot>
    <SharedDebugOutputRoot Condition="'$(UseSharedOutputPath)' == 'true' and '$(MSBuildProjectName)' == 'NgXmlBuilder'">BuildNgXmlBuilder</SharedDebugOutputRoot>
    <SharedReleaseOutputRoot Condition="'$(UseSharedOutputPath)' == 'true' and '$(MSBuildProjectName)' == 'NgXmlBuilder'">BuildNgXmlBuilderRelease</SharedReleaseOutputRoot>
  </PropertyGroup>

  <PropertyGroup>
    <Version>2.1</Version>
    <Company>Tomb Engine Team</Company>
    <Copyright>Copyright © Tomb Engine Team 2017 - 2026</Copyright>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug' and '$(UseSharedOutputPath)' == 'true'">
    <OutputPath>$(MSBuildThisFileDirectory)$(SharedDebugOutputRoot) ($(NormalizedPlatform))\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(UseSharedOutputPath)' == 'true'">
    <OutputPath>$(MSBuildThisFileDirectory)$(SharedReleaseOutputRoot) ($(NormalizedPlatform))\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'x86'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
