//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TombIDE.Shared.Scripting.Syntaxes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OldCommandSyntaxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OldCommandSyntaxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TombIDE.Shared.Scripting.Syntaxes.OldCommandSyntaxes", typeof(OldCommandSyntaxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] AnimatingMIP= {SLOT (1-16)}, {DISTANCE (Sectors)}.
        /// </summary>
        public static string AnimatingMIP {
            get {
                return ResourceManager.GetString("AnimatingMIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] ColAddHorizon= ENABLED / DISABLED.
        /// </summary>
        public static string ColAddHorizon {
            get {
                return ResourceManager.GetString("ColAddHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PCExtensions] Cut= .TR4 ; Default value.
        /// </summary>
        public static string CutPC {
            get {
                return ResourceManager.GetString("CutPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSXExtensions] Cut= .CUT ; Default value.
        /// </summary>
        public static string CutPSX {
            get {
                return ResourceManager.GetString("CutPSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] DemoDisc= ENABLED / DISABLED.
        /// </summary>
        public static string DemoDisc {
            get {
                return ResourceManager.GetString("DemoDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Examine= {TYPE (1-3)}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string Examine {
            get {
                return ResourceManager.GetString("Examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Language] File= {UNIQUE_ID}, {FILE_NAME}.TXT.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] FlyCheat= ENABLED / DISABLED.
        /// </summary>
        public static string FlyCheat {
            get {
                return ResourceManager.GetString("FlyCheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PCExtensions] FMV= .BIK ; Default value.
        /// </summary>
        public static string FMVPC {
            get {
                return ResourceManager.GetString("FMVPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSXExtensions] FMV= .FMV ; Default value.
        /// </summary>
        public static string FMVPSX {
            get {
                return ResourceManager.GetString("FMVPSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Fog= {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}.
        /// </summary>
        public static string Fog {
            get {
                return ResourceManager.GetString("Fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Horizon= ENABLED / DISABLED.
        /// </summary>
        public static string Horizon {
            get {
                return ResourceManager.GetString("Horizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] InputTimeout= {NUM_OF_FRAMES}.
        /// </summary>
        public static string InputTimeout {
            get {
                return ResourceManager.GetString("InputTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Key= {1-12}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] KeyCombo= {1-8}, {1-2}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string KeyCombo {
            get {
                return ResourceManager.GetString("KeyCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Layer1= {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}, {SPEED}.
        /// </summary>
        public static string Layer1 {
            get {
                return ResourceManager.GetString("Layer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Legend= {MESSAGE_STRING}.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] LensFlare= {GLOBAL_COORD_X}, {GLOBAL_COORD_Y}, {GLOBAL_COORD_Z}, {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}.
        /// </summary>
        public static string LensFlare {
            get {
                return ResourceManager.GetString("LensFlare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Level= {LEVEL_PATH}, {SOUND_ID}.
        /// </summary>
        public static string LevelLevel {
            get {
                return ResourceManager.GetString("LevelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PCExtensions] Level= .TR4 ; Default value.
        /// </summary>
        public static string LevelPC {
            get {
                return ResourceManager.GetString("LevelPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSXExtensions] Level= .PSX ; Default value.
        /// </summary>
        public static string LevelPSX {
            get {
                return ResourceManager.GetString("LevelPSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Lightning= ENABLED / DISABLED.
        /// </summary>
        public static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] LoadCamera= {SOURCE_X_POS}, {SOURCE_Y_POS}, {SOURCE_Z_POS}, {TARGET_X_POS}, {TARGET_Y_POS}, {TARGET_Z_POS}, {ROOM_NUMBER}.
        /// </summary>
        public static string LoadCamera {
            get {
                return ResourceManager.GetString("LoadCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] LoadSave= ENABLED / DISABLED.
        /// </summary>
        public static string LoadSave {
            get {
                return ResourceManager.GetString("LoadSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Mirror= {ROOM_NUMBER}, {ROOM_ORIGIN}.
        /// </summary>
        public static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Name= {NAME_STRING}.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Pickup= {1-4}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] PickupCombo= {1-4}, {1-2}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string PickupCombo {
            get {
                return ResourceManager.GetString("PickupCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] PlayAnyLevel= ENABLED / DISABLED.
        /// </summary>
        public static string PlayAnyLevel {
            get {
                return ResourceManager.GetString("PlayAnyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Puzzle= {1-12}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] PuzzleCombo= {1-8}, {1-2}, {NAME}, {HEIGHT}, {SIZE}, {X_ORIENT}, {Y_ORIENT}, {Z_ORIENT}, {BIT_MASK}.
        /// </summary>
        public static string PuzzleCombo {
            get {
                return ResourceManager.GetString("PuzzleCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] RemoveAmulet= ENABLED / DISABLED.
        /// </summary>
        public static string RemoveAmulet {
            get {
                return ResourceManager.GetString("RemoveAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] ResetHUB= {LEVEL_ID}.
        /// </summary>
        public static string ResetHUB {
            get {
                return ResourceManager.GetString("ResetHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] ResidentCut= {TRIGGER_ID}, {CUTSCENE_ID}.
        /// </summary>
        public static string ResidentCut {
            get {
                return ResourceManager.GetString("ResidentCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Timer= ENABLED / DISABLED.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options] Title= ENABLED / DISABLED.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] Train= ENABLED / DISABLED.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] UVrotate= {SPEED}.
        /// </summary>
        public static string UVRotate {
            get {
                return ResourceManager.GetString("UVRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Level] YoungLara= ENABLED / DISABLED.
        /// </summary>
        public static string YoungLara {
            get {
                return ResourceManager.GetString("YoungLara", resourceCulture);
            }
        }
    }
}
