<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>TombIDE Library Registration</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="COM\Comdlg32.ocx" />
    <EmbeddedResource Include="COM\Mscomctl.ocx" />
    <EmbeddedResource Include="COM\PicFormat32.ocx" />
    <EmbeddedResource Include="COM\Richtx32.ocx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TombIDE.Shared\TombIDE.Shared.csproj" />
  </ItemGroup>
</Project>