<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="MdXaml" Version="1.27.0" />
    <PackageReference Include="TextMateSharp" Version="2.0.3" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Bases\ContentNodesProviderBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Workers\ContentChangedWorker.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Workers\ErrorDetectionWorker.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\ExtendedDarkDataGridView.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
    <ProjectReference Include="..\TombLib\TombLib.csproj" />
    <ProjectReference Include="..\TombLib.WPF\TombLib.WPF.csproj" />
  </ItemGroup>
</Project>