name: Bug report
description: Create a report to help us understand and triage your issue.
title: "[ Bug Report ] "
labels: 
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please follow this document carefully to report a bug.

  - type: dropdown
    attributes:
      label: Tomb Editor Version
      description: |
        Please select the Tomb Editor version you are using.
      options:
        - v2.0 Release Candidate 1
        - v1.11 (latest public release)
        - v1.10.1 or earlier 
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Game Engine
      description: |
        Please select the game engine you are using. This is so we can determine if the issue is engine-specific or editor-specific.
      options:
        - Tomb Engine
        - TRNG / TRNG-CE
        - TRX
        - Other legacy Engine (TR1-TR5)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: |
        Please provide a clear and concise description of what the issue is.
      placeholder: |
        Your bug report here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Please provide detailed steps to reproduce the issue. A screen recording can be submitted as an alternative to written steps.

        **Note**: If the bug cannot be reproduced or the issue is not clearly explained, it may be closed without further investigation.
      placeholder: |
        Step-by-step reproduction instructions here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: |
        What did you expect to happen?

        **Note**: If the bug cannot be reproduced or the issue is not clearly explained, it may be closed without further investigation.
      placeholder: |
        A description of what should happen here.
    validations:
      required: true
