name: Feature Request
description: Suggest an idea for the Tomb Editor Toolchain
title: "[ Feature Request ] "
labels: new feature

body:
- type: dropdown
  attributes:
    label: Tomb Editor Toolchain Application
    description: |
      Please select the which application you are making the feature request for.
    options:
      - Tomb Editor
      - WadTool
      - SoundTool
      - Tomb IDE 
  validations:
    required: true

- type: dropdown
  attributes:
    label: Tomb Editor Toolchain Version
    description: |
      Please select the Tomb Editor version you are using.
    options:
      - v2.0 Release Candidate 1
      - v1.11 (latest public release)
      - v1.10.1  
  validations:
    required: true

- type: dropdown
  attributes:
    label: Game Engine
    description: |
      Please select the game engine you are using. This is to provide further context and different engines have different editor features.
    options:
      - Tomb Engine
      - TRX
      - TRNG / TRNG-CE
      - Other legacy Engine (TR1-TR5)
  validations:
    required: true

- type: textarea
  attributes:
    label: Please describe your feature request and the problem it solves
    placeholder: "I would like for Tomb Editor to do x because of y..."
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context or screenshots about the feature request here. Video files may need to be uploaded to a file sharing service that does not expire (Google Drive, Dropbox, etc.) and then linked here.
  validations:
    required: false
