<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
    <PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
    <Compile Update="ContentNodes\TRXNodesProvider.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TombLib.Scripting.Specifications\TombLib.Scripting.Specifications.csproj" />
    <ProjectReference Include="..\TombLib.Scripting.UI\TombLib.Scripting.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Icons\Constant.png" />
    <Resource Include="Resources\Icons\Property.png" />
    <Resource Include="Resources\Icons\Array.png" />
  </ItemGroup>
</Project>