using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TombLib.NG
{
    public enum NgListKind
    {
        FogColors,
        Percentage,
        Slots,
        StaticSlots,
        Transparency32,
        BitList,
        NegativeNumbers,
        CollisionFloor,
        CollisionCeiling,
        MemoryInventoryIndices,
        MicroClicks,
        MemoryAnimation,
        MemoryInventory,
        MemorySlot,
        MemoryCode,
        MemoryItem,
        MemorySave,
        VarText,
        LongStore,
        VarStore,
        VarNormals,
        FlybySequences,
        FogDistances,
        TextureSequence128,
        BackupGames,
        TimerSignedLong,
        TimerSigned,
        OtherLaraSlots,
        SlotMoveables,
        SlotSTandardMeshes,
        SlotSwapMeshes,
        CameraEffects,
        Flyby,
        StaticsList,
        Sink,
        ButtonsList,
        Recharge,
        Inventory,
        Moveables,
        Degrees,
        Sequence32,
        Sequence128,
        Colors,
        InventoryIndex,
        Frag2x2,
        Frag3x3,
        Frag4x4,
        HalfClicks,
        HalfClicks32,
        Time128,
        AnimationRanges,
        PsxStrings,
        PcStrings,
        StringList255,
        NgStringList255,
        NgAllStrings,
        CdTracks,
        FmvList,
        SoundEffectsA,
        SoundEffectsB,
        Sfx1024,
        TimeList32,
        Animation32A,
        Animation32B,
        Animation32C,
        Animation255,
        AnimationLaraB,
        StateId,
        SlotAnimLara,
        AddEffect,
        ClickDistance32,
        OcbLaraStart,
        RoomList255,
        KeyboardMode
    }
}
