using System;
using System.Collections.Generic;
using System.Linq;

namespace TombLib.LevelData.Compilers.TombEngine
{
    /// <summary>
    /// TombEngine Pathfinding System - Zone Generation
    ///
    /// This file handles the high-level pathfinding data generation for TombEngine.
    ///
    /// ARCHITECTURE OVERVIEW:
    /// =====================
    /// 1. BOXES: Rectangular floor regions where enemies can walk. Generated by Dec_BuildBoxesAndOverlaps().
    /// 2. OVERLAPS: Connections between adjacent boxes. Define which boxes are reachable from each other.
    /// 3. ZONES: Groups of interconnected boxes based on enemy movement capabilities.
    ///
    /// The zone system allows the game engine to quickly determine if an enemy can reach
    /// a target location without performing expensive pathfinding calculations.
    ///
    /// COORDINATE SYSTEM:
    /// ==================
    /// - X axis: horizontal (left/right in 2D view)
    /// - Z axis: horizontal (up/down in 2D view), Z=0 at bottom
    /// - Y axis: vertical (height), negative values are higher
    /// </summary>
    public sealed partial class LevelCompilerTombEngine
    {
        /// <summary>
        /// Defines the movement capabilities of different enemy types.
        /// Each zone type creates separate connectivity groups for AI pathfinding.
        ///
        /// The zone system allows quick lookup: if two boxes have the same zone number
        /// for a given ZoneType, an enemy of that type can pathfind between them.
        /// </summary>
        public enum ZoneType
        {
            /// <summary>
            /// Zone 0: Skeleton-type enemies.
            /// - Can climb 1 click (256 units) height difference
            /// - Can jump across 1-2 sector gaps
            /// - Cannot enter water
            /// - Cannot use monkey swing
            /// Examples: Skeletons in TR4/TR5
            /// </summary>
            Skeleton,

            /// <summary>
            /// Zone 1: Basic ground enemies.
            /// - Can climb 1 click (256 units) height difference
            /// - Cannot jump gaps
            /// - Cannot enter water
            /// - Cannot use monkey swing
            /// Examples: Scorpions, mummies, dogs, wild boars
            /// </summary>
            Basic,

            /// <summary>
            /// Zone 2: Underwater enemies.
            /// - Stay in water only (cannot go on land)
            /// - No step height limit (act like flyers in water)
            /// - Can traverse slopes
            /// Examples: Fish, piranhas
            /// </summary>
            Water,

            /// <summary>
            /// Zone 3: Amphibious enemies.
            /// - Can cross water/land boundary freely
            /// - On land: can climb 1 click height difference
            /// - In water: no step limit (act like flyers)
            /// - Can traverse slopes in water
            /// Examples: Crocodiles
            /// </summary>
            Amphibious,

            /// <summary>
            /// Zone 4: Human-type enemies (most capable).
            /// - Can climb 4 clicks (1024 units = 1 sector) height difference
            /// - Can jump across 1-2 sector gaps
            /// - Can use monkey swing to cross water boundaries
            /// - Cannot enter water otherwise
            /// Examples: Baddy 1 &amp; 2, guards, soldiers
            /// </summary>
            Human,

            /// <summary>
            /// Zone 5: Flying enemies.
            /// - No height restrictions
            /// - Cannot enter water rooms
            /// - Can traverse any land terrain regardless of slopes
            /// Examples: Bats, harpies, demigods (flying mode)
            /// </summary>
            Flyer
        }

        /// <summary>
        /// Main entry point for pathfinding data generation.
        ///
        /// This method orchestrates the entire pathfinding compilation process:
        /// 1. Fixes monkey swing flags on floor portals (inherited from rooms below)
        /// 2. Generates boxes and overlaps (Dec_BuildBoxesAndOverlaps)
        /// 3. Converts internal box format to TombEngine format
        /// 4. Builds zone connectivity for each enemy type (6 zone types x 2 flip states = 12 zone sets)
        ///
        /// OUTPUT DATA STRUCTURES:
        /// - _boxes: List of TombEngineBox (walkable rectangular areas)
        /// - _overlaps: List of TombEngineOverlap (connections between boxes with flags)
        /// - _zones: List of TombEngineZoneGroup (zone numbers per box for each enemy type)
        /// </summary>
        private void BuildPathFindingData()
        {
            ReportProgress(48, "Building pathfinding data");

            // ===================================================================================
            // PHASE 1: Fix monkey swing flags on floor portals
            // ===================================================================================
            // When a sector has a floor portal, the monkey swing flag may be defined in a room below.
            // This pass ensures monkey swing info is correctly propagated through portal chains.
            foreach (var fixRoom in _tempRooms.Values)
            {
                for (int x = 0; x < fixRoom.NumXSectors; x++)
                {
                    for (int z = 0; z < fixRoom.NumZSectors; z++)
                    {
                        var sector = fixRoom.AuxSectors[x, z];
                        if (sector.FloorPortal != null)
                            sector.Monkey = FindMonkeyFloor(fixRoom.OriginalRoom, x, z);
                    }
                }
            }

            // ===================================================================================
            // PHASE 2: Generate boxes and overlaps
            // ===================================================================================
            // This creates dec_boxes and dec_overlaps lists.
            Dec_BuildBoxesAndOverlaps();

            // ===================================================================================
            // PHASE 3: Convert to TombEngine format
            // ===================================================================================
            // Convert internal overlap format to final format
            _overlaps = new List<TombEngineOverlap>();
            _overlaps.AddRange(dec_overlaps);

            // Convert internal box format to TombEngine format
            _boxes = new List<TombEngineBox>();
            _zones = new List<TombEngineZoneGroup>();

            for (var i = 0; i < dec_boxes.Count; i++)
            {
                int flags = 0;

                if (dec_boxes[i].Splitter)
                    flags |= BoxFlags.Splitter;

                if (dec_boxes[i].Water)
                    flags |= BoxFlags.Water;

                if (dec_boxes[i].Shallow)
                    flags |= BoxFlags.Shallow;

                var box = new TombEngineBox()
                {
                    Xmin = dec_boxes[i].Xmin,                              // Left boundary (in sectors)
                    Xmax = dec_boxes[i].Xmax,                              // Right boundary (in sectors)
                    Zmin = dec_boxes[i].Zmin,                              // Bottom boundary (in sectors)
                    Zmax = dec_boxes[i].Zmax,                              // Top boundary (in sectors)
                    TrueFloor = -dec_boxes[i].Height,                      // Floor height (negated: TR uses inverted Y)
                    OverlapIndex = dec_boxes[i].OverlapIndex,              // Index into _overlaps array (-1 if none)
                    Flags = flags
                };

                _boxes.Add(box);

                // Create corresponding zone group (one per box)
                var zone = new TombEngineZoneGroup();
                _zones.Add(zone);
            }

            // ===================================================================================
            // PHASE 4: Build zones for each enemy type
            // ===================================================================================
            // Zones group boxes that are reachable from each other for a specific enemy type.
            // Two boxes with the same zone number can be pathfound between by that enemy type.
            //
            // Zone generation is done separately for:
            // - Unflipped rooms (group 0): Normal room state
            // - Flipped rooms (group 1): Alternate/flipped room state
            //
            // This allows enemies to correctly pathfind in both room states.
            var zoneTypes = Enum.GetValues(typeof(ZoneType));

            foreach (bool flipped in new[] { false, true })
            {
                int group = Convert.ToInt32(flipped);  // 0 for unflipped, 1 for flipped

                // Zone counter for each zone type (starts at 1, zone 0 is reserved/invalid)
                var zoneCount = Enumerable.Repeat(1, zoneTypes.Length).ToArray();

                // Process each box
                for (var i = 0; i < _zones.Count; i++)
                {
                    // Process each zone type
                    foreach (var zoneType in (ZoneType[])zoneTypes)
                    {
                        // If this box hasn't been assigned a zone yet for this type
                        if (_zones[i].Zones[group][(int)zoneType] == int.MaxValue)
                        {
                            // Assign new zone number to this box
                            _zones[i].Zones[group][(int)zoneType] = zoneCount[(int)zoneType];

                            // Find all boxes reachable from this box and assign same zone
                            // This uses flood-fill through overlaps with movement constraints
                            foreach (var box in GetAllReachableBoxes(i, zoneType, flipped))
                            {
                                if (_zones[box].Zones[group][(int)zoneType] == int.MaxValue)
                                    _zones[box].Zones[group][(int)zoneType] = zoneCount[(int)zoneType];
                            }

                            // Increment zone counter for next disconnected region
                            zoneCount[(int)zoneType]++;
                        }
                    }
                }
            }

            ReportProgress(52, "    Number of boxes/zones: " + _boxes.Count);
            ReportProgress(52, "    Number of overlaps: " + _overlaps.Count);
        }

        /// <summary>
        /// Finds all boxes reachable from a starting box for a specific enemy type.
        ///
        /// This implements a non-recursive flood-fill algorithm through the overlap graph,
        /// filtering connections based on the movement capabilities of the enemy type.
        ///
        /// ALGORITHM:
        /// 1. Start with the given box on a stack
        /// 2. Pop a box, iterate through its overlaps
        /// 3. For each connected box, check if the enemy type can traverse the connection
        /// 4. If yes, add to result and push onto stack for further exploration
        /// 5. Continue until stack is empty
        ///
        /// OVERLAP FLAGS:
        /// - 0x0800: Jump connection (boxes separated by 1-2 sector gap)
        /// - 0x2000: Monkey swing connection (ceiling traversal)
        /// - 0x8000: End of overlap list marker
        /// </summary>
        /// <param name="box">Starting box index</param>
        /// <param name="zoneType">Enemy movement type to check connectivity for</param>
        /// <param name="flipped">Whether to use flipped room state</param>
        /// <returns>Collection of all box indices reachable from the starting box</returns>
        private IEnumerable<int> GetAllReachableBoxes(int box, ZoneType zoneType, bool flipped)
        {
            var boxes = new List<int>();

            // Boxes with no overlaps (isolated) have overlapIndex = -1
            if (_boxes[box].OverlapIndex < 0)
                return boxes;

            // Non-recursive flood-fill using explicit stack (avoids stack overflow on large levels)
            var stack = new Stack<int>();
            stack.Push(box);

            // Determine if starting box is in water - used for water boundary checks
            var isWater = dec_boxes[box].Water;

            while (stack.Count > 0)
            {
                var next = stack.Pop();
                var last = false;  // Tracks if we've reached the end of this box's overlap list

                // Iterate through overlaps starting at this box's overlap index
                // Overlaps for a box are stored contiguously, ending with 0x8000 flag
                for (int i = _boxes[next].OverlapIndex; i < _overlaps.Count && !last; i++)
                {
                    int overlapIndex = i;
                    if (overlapIndex < 0)
                        return boxes;

                    // Check for end-of-list marker (0x8000 = END_BIT)
                    last = (_overlaps[overlapIndex].Flags & OverlapFlags.End) != 0;

                    // Extract overlap capability flags
                    bool canJump = (_overlaps[overlapIndex].Flags & OverlapFlags.Jump) != 0;      // JUMP_BIT
                    bool canMonkey = (_overlaps[overlapIndex].Flags & OverlapFlags.Monkey) != 0;  // MONKEY_BIT
                    bool canTraverseAmphibious = (_overlaps[overlapIndex].Flags & OverlapFlags.AmphibiousTraversable) != 0;

                    var boxIndex = _overlaps[overlapIndex].Box;

                    // =======================================================================
                    // FILTER 1: Flip state compatibility
                    // =======================================================================
                    // Box must exist in the current flip state to be reachable
                    bool sameFlip = (!flipped && dec_boxes[boxIndex].Unflipped || flipped && dec_boxes[boxIndex].Flipped);
                    if (!sameFlip)
                        continue;

                    // Get target box properties
                    bool water = dec_boxes[boxIndex].Water;
                    int step = Math.Abs(_boxes[next].TrueFloor - _boxes[boxIndex].TrueFloor);

                    // =======================================================================
                    // FILTER 2: Slope check
                    // =======================================================================
                    // Most enemies cannot walk on steep slopes (gradient >= 3 clicks)
                    // Exception: Flyers (no ground movement), Amphibious and Water enemies (swimming)
                    bool landZone = zoneType != ZoneType.Flyer && zoneType != ZoneType.Water && zoneType != ZoneType.Amphibious;
                    if (landZone && dec_boxes[boxIndex].Slope)
                        continue;

                    // =======================================================================
                    // FILTER 3: Water boundary check
                    // =======================================================================
                    // Most enemies cannot cross water/land boundary
                    // Exceptions:
                    // - Amphibious: Can freely cross (crocodiles)
                    // - Human + monkey swing: Can cross via ceiling (but not swimming)
                    bool canCrossWater = (zoneType == ZoneType.Amphibious) ||
                                         (zoneType == ZoneType.Human && canMonkey);

					// Enemies that can't cross land/water boundary can traverse shallow water
                    bool shallowOverlap = (dec_boxes[boxIndex].Shallow && dec_boxes[box].Shallow) ||
                                          (dec_boxes[boxIndex].Shallow && !dec_boxes[box].Water) ||
                                          (dec_boxes[box].Shallow && !dec_boxes[boxIndex].Water);

                    shallowOverlap = landZone && shallowOverlap;

                    if (water != isWater && !canCrossWater && !shallowOverlap)
                        continue;

                    // =======================================================================
                    // FILTER 4: Movement capability check (zone-type specific)
                    // =======================================================================
                    bool add = false;

                    switch (zoneType)
                    {
                        case ZoneType.Skeleton:
                            // Skeletons: 1 click step OR can jump gaps
                            // Step limit: 256 world units (1 click)
                            add = (step <= Clicks.ToWorld(1) || canJump);
                            break;

                        case ZoneType.Basic:
                            // Basic enemies: 1 click step only, no special movement
                            // Most limited ground enemy type
                            add = (step <= Clicks.ToWorld(1));
                            break;

                        case ZoneType.Water:
                            // Water enemies: No step limit (3D swimming movement)
                            // Already filtered to water-only boxes above
                            add = true;
                            break;

                        case ZoneType.Amphibious:
                            // Amphibious: 1 click step and non-slope on land, no limit in water
                            // Can transition between water and land boxes
                            add = canTraverseAmphibious || (isWater && (water == isWater)) ||
                                  (!(dec_boxes[boxIndex].Slope && !dec_boxes[boxIndex].Water) && step <= Clicks.ToWorld(1));
                            break;

                        case ZoneType.Human:
                            // Human enemies: 4 click step (1 sector), can jump, can monkey
                            // Most capable land enemy type
                            // Step limit: 1024 world units (1 sector = 4 clicks)
                            add = (step <= (int)Level.SectorSizeUnit || canJump || canMonkey);
                            break;

                        case ZoneType.Flyer:
                            // Flyers: No step limit (3D flight)
                            // Already filtered to non-water boxes above
                            add = true;
                            break;

                        default:
                            logger.Error("Unknown zone specified for box " + box);
                            break;
                    }

                    // Skip if already on stack or failed movement check
                    if (stack.Contains(boxIndex) || !add)
                        continue;

                    // Add to exploration stack and result list
                    if (!boxes.Contains(boxIndex))
                        stack.Push(boxIndex);

                    boxes.Add(boxIndex);
                }
            }

            // Remove any duplicates (shouldn't happen, but defensive)
            return boxes.Distinct();
        }
    }
}
