namespace ScriptLib.IniScript;

public static class IniScriptLanguageConstants
{
	public static readonly string[] Sections =
	[
		"Language",
		"Level",
		"Options",
		"PCExtensions",
		"PSXExtensions",
		"Title",
		"Strings",
		"PSXStrings",
		"PCStrings",
		"ExtraNG"
	];

	public static readonly string[] NewCommands =
	[
		"AddEffect",
		"Animation",
		"AnimationSlot",
		"AssignSlot",
		"ColorRGB",
		"CombineItems",
		"CRS",
		"Customize",
		"CutScene",
		"Damage",
		"DefaultWindowsFont",
		"Demo",
		"Detector",
		"Diagnostic",
		"DiagnosticType",
		"Diary",
		"Elevator",
		"Enemy",
		"Equipment",
		"FogRange",
		"ForceBumpMapping",
		"ForceVolumetricFX",
		"GlobalTrigger",
		"Image",
		"ImportFile",
		"ItemGroup",
		"KeyPad",
		"LaraStartPos",
		"LevelFarView",
		"LogItem",
		"MirrorEffect",
		"MultEnvCondition",
		"NewSoundEngine",
		"Organizer",
		"Parameters",
		"Plugin",
		"PreserveInventory",
		"Rain",
		"SavegamePanel",
		"Settings",
		"ShowLaraInTitle",
		"Snow",
		"SoundSettings",
		"StandBy",
		"StaticMIP",
		"Switch",
		"TestPosition",
		"TextFormat",
		"TextureSequence",
		"TriggerGroup",
		"Turbo",
		"WindowsFont",
		"WindowTitle",
		"WorldFarView"
	];

	public static readonly string[] OldCommands =
	[
		"AnimatingMIP",
		"ColAddHorizon",
		"DemoDisc",
		"Examine",
		"FlyCheat",
		"Fog",
		"Horizon",
		"InputTimeout",
		"Key",
		"KeyCombo",
		"Layer1",
		"Legend",
		"LensFlare",
		"Level",
		"Lightning",
		"LoadCamera",
		"LoadSave",
		"Mirror",
		"Name",
		"Pickup",
		"PickupCombo",
		"PlayAnyLevel",
		"Puzzle",
		"PuzzleCombo",
		"RemoveAmulet",
		"ResetHUB",
		"ResidentCut",
		"Timer",
		"Title",
		"Train",
		"UVRotate",
		"YoungLara",

		// Not sure where these belong
		"Cut",
		"File",
		"FMV",

		// Unknown
		"Layer2",
		"NoLevel",
		"Pulse",
		"Security",
		"StarField"
	];
}
