<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CustomTabControl">
      <HintPath>..\..\Libs\CustomTabControl.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Settings\TRXSettingsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="TRXStudio.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="GameFlowScriptStudio.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Settings\GameFlowSettingsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Settings\ClassicScriptSettingsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ToolWindows\ContentExplorer.cs" />
    <Compile Update="ToolWindows\SearchResults.cs" />
    <Compile Update="Controls\EditorTabControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\SearchTextBox.cs" />
    <Compile Update="ToolStrips\StudioStatusStrip.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ToolStrips\EditorContextMenu.cs" />
    <Compile Update="ToolWindows\CompilerLogs.cs" />
    <Compile Update="ToolWindows\FileExplorer.cs" />
    <Compile Update="ToolWindows\ReferenceBrowser.cs" />
    <Compile Update="Controls\SyntaxPreview.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="ToolStrips\StudioMenuStrip.cs" />
    <Compile Update="ToolStrips\StudioToolStrip.cs" />
    <Compile Update="Bases\StudioBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="ClassicScriptStudio.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="LuaStudio.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DarkUI\DarkUI.WPF\DarkUI.WPF.csproj" />
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.LanguageServer.Lua\TombLib.LanguageServer.Lua.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.Core\TombLib.Scripting.Core.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.GameFlowScript\TombLib.Scripting.GameFlowScript.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.ClassicScript\TombLib.Scripting.ClassicScript.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.Lua\TombLib.Scripting.Lua.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.Specifications\TombLib.Scripting.Specifications.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.TRX\TombLib.Scripting.TRX.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.UI\TombLib.Scripting.UI.csproj" />
    <ProjectReference Include="..\TombIDE.Shared\TombIDE.Shared.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Forms\TombLib.Forms.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib\TombLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\ClassicScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\GameFlowScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\Lua.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\PlainText.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\Strings.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ContextMenus\TRX.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\ClassicScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\GameFlowScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\Lua.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\PlainText.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\Strings.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\MenuStrips\TRX.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\ClassicScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\GameFlowScript.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\Lua.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\PlainText.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\Strings.xml" />
    <EmbeddedResource Include="UI\DocumentModePresets\ToolStrips\TRX.xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="FileHandling.cs" />
    <Compile Remove="StudioBase.cs" />
    <Compile Remove="StudioBase.Designer.cs" />
    <Compile Remove="UI\DocumentModePresets\MenuStripPresets.cs" />
    <Compile Remove="UI\DocumentModePresets\ToolStripPresets.cs" />
    <Compile Remove="UI\StudioModePresets\MenuStripPresets.cs" />
    <Compile Remove="UI\StudioModePresets\ToolStripPresets.cs" />
    <Compile Remove="UI\UIElement.cs" />
    <EmbeddedResource Remove="StudioBase.resx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>