<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Product>TombIDE Scripting Studio Module</Product>
    <AssemblyTitle>$(Product)</AssemblyTitle>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CustomTabControl">
      <HintPath>..\..\Libs\CustomTabControl.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.74.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.5.0" />
    <PackageReference Include="StreamJsonRpc" Version="2.24.84" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="DocumentOutline\DocumentOutlineToolWindow.cs" />
    <Compile Update="ToolStrips\StudioStatusStrip.cs" />
    <Compile Update="Build\CompilerLogsToolWindow.cs" />
    <Compile Update="FileExplorer\FileExplorerToolWindow.cs" />
    <Compile Update="Navigation\ReferenceBrowserToolWindow.cs" />
    <Compile Update="ToolStrips\StudioMenuStrip.cs" />
    <Compile Update="ToolStrips\StudioToolStrip.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DarkUI\DarkUI.WPF\DarkUI.WPF.csproj" />
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
    <Reference Include="Nickelony.LanguageServer.Abstractions">
      <HintPath>..\..\Libs\Nickelony.LanguageServer.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Nickelony.LanguageServer.Client">
      <HintPath>..\..\Libs\Nickelony.LanguageServer.Client.dll</HintPath>
    </Reference>
    <Reference Include="Nickelony.LanguageServer.Lua">
      <HintPath>..\..\Libs\Nickelony.LanguageServer.Lua.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting\TombLib.Scripting.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.GameFlowScript\TombLib.Scripting.GameFlowScript.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.ClassicScript\TombLib.Scripting.ClassicScript.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.Lua\TombLib.Scripting.Lua.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.TRX\TombLib.Scripting.TRX.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Scripting.UI\TombLib.Scripting.UI.csproj" />
    <ProjectReference Include="..\TombIDE.Shared\TombIDE.Shared.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib.Forms\TombLib.Forms.csproj" />
    <ProjectReference Include="..\..\TombLib\TombLib\TombLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>