//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandToolTips() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptEditor.Resources.CommandToolTips", typeof(CommandToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string Ambient {
            get {
                return ResourceManager.GetString("Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a When the game displays ANIMATING[1-16] objects,
        ///it will display the corresponding ANIMATING[1-16]_MIP object when Lara (actually her chase camera)
        ///is at a certain distance away from them.
        ///
        ///The MIP objects are low-resolution polygon models that will use fewer resources.
        ///Distance works by blocks, so a value of 1 shows the MIP until Lara is about 1 block away.
        ///When she gets within that range, the MIP swaps with the actual object.
        ///A value of 2 makes it 2 blocks, 3 makes it 3 blocks and so forth.
        ///
        ///Usage:
        ///Animati [stringa troncata]&quot;;.
        /// </summary>
        internal static string AnimatingMIP {
            get {
                return ResourceManager.GetString("AnimatingMIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables additive blending to semi-transparent textures assigned to the HORIZON object.
        ///Remember, textures above the sky-sprite need to be assigned as Semi-Transparent, or the sky-sprite will not be visible.
        ///
        ///Usage:
        ///ColAddHorizon = ENABLED / DISABLED.
        /// </summary>
        internal static string ColAddHorizon {
            get {
                return ResourceManager.GetString("ColAddHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specifies that the SCRIPT.txt file is for a demo,
        ///therefore the resulting SCRIPT.dat file will only have a title level and one playable level specified (the first one defined)
        ///regardless of how many playable levels are defined in the SCRIPT.txt file.
        ///
        ///Usage:
        ///DemoDisc = ENABLED / DISABLED.
        /// </summary>
        internal static string DemoDisc {
            get {
                return ResourceManager.GetString("DemoDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information about the EXAMINE[1-3] collectible items.
        ///
        ///The first parameter is the number of the EXAMINE object in the wad file.
        ///The second parameter is its name displayed in the inventory and must be identical to a string in the ENGLISH.txt file.
        ///
        ///The {HEIGHT} parameter adjusts the height of the object viewed in the inventory.
        ///It calculates the position of the center of rotation from the top of the screen, converted in hexadecimal value.
        ///The larger the number, the lower the object.
        ///You can also use negative [stringa troncata]&quot;;.
        /// </summary>
        internal static string Examine {
            get {
                return ResourceManager.GetString("Examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables the DOZY cheat.
        ///
        ///Usage:
        ///FlyCheat = ENABLED / DISABLED.
        /// </summary>
        internal static string FlyCheat {
            get {
                return ResourceManager.GetString("FlyCheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set distance fog color for the current level.
        ///Distance Fog is visible only if VOLUMETRIC FX are disabled in the setup
        ///or if the level is set in TRAIN mode (in which Volumetric Effects are disabled by default).
        ///
        ///Usage:
        ///Fog = {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}.
        /// </summary>
        internal static string FOG {
            get {
                return ResourceManager.GetString("FOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables the Skybox.
        ///The game will display the HORIZON object in every room where the Skybox is set as visible.
        ///
        ///Usage:
        ///Horizon = ENABLED / DISABLED.
        /// </summary>
        internal static string Horizon {
            get {
                return ResourceManager.GetString("Horizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specifies the number of tick frames after which the game enters demo mode if the player doesn’t press any key.
        ///
        ///Usage:
        ///InputTimeout = {NUM_OF_FRAMES}.
        /// </summary>
        internal static string InputTimeout {
            get {
                return ResourceManager.GetString("InputTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string KeyCombo {
            get {
                return ResourceManager.GetString("KeyCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string LaraType {
            get {
                return ResourceManager.GetString("LaraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sets the color and speed of the scrolling sky texture.
        ///Accepted values of speed are in a range between -16 and 16.
        ///
        ///Layer1 = {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}, {SPEED}.
        /// </summary>
        internal static string Layer1 {
            get {
                return ResourceManager.GetString("Layer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Displays a string of text on the bottom of the screen at the start of the level.
        ///The string must be identical to a string in the ENGLISH.txt file.
        ///
        ///Usage:
        ///Legend = {MESSAGE_STRING}.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables a global Lens Flare in the level.
        ///The Lens Flare can be seen anywhere inside the level as long as it’s in a visible patch of sky.
        ///The origin of the Lens Flare is set in global level coordinates.
        ///Enable FlyCheat mode and press F1 to display global coordinates in game.
        ///
        ///Usage:
        ///LensFlare = {GLOBAL_COORD_X}, {GLOBAL_COORD_Y}, {GLOBAL_COORD_Z}, {RED_VALUE}, {GREEN_VALUE}, {BLUE_VALUE}.
        /// </summary>
        internal static string LensFlare {
            get {
                return ResourceManager.GetString("LensFlare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Defines the .TR4 level path and the ambient sound used at the start of the level.
        ///Level files are mainly stored in the game&apos;s &quot;DATA&quot; folder.
        ///
        ///Usage:
        ///Level = {LEVEL_PATH}, {SOUND_ID}.
        /// </summary>
        internal static string LevelLevel {
            get {
                return ResourceManager.GetString("LevelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2.
        /// </summary>
        internal static string LevelPC {
            get {
                return ResourceManager.GetString("LevelPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1.
        /// </summary>
        internal static string LevelPSX {
            get {
                return ResourceManager.GetString("LevelPSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3.
        /// </summary>
        internal static string LevelTitle {
            get {
                return ResourceManager.GetString("LevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables thunderstorm.
        ///The background audio will include thunder sounds and the sky texture will flash to simulate lightning.
        ///
        ///Usage:
        ///Lightning = ENABLED / DISABLED.
        /// </summary>
        internal static string Lightning {
            get {
                return ResourceManager.GetString("Lightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sets the framing to display during the ‘Load Game’ screen in game.
        ///The position of the camera and the target are set in global level coordinates.
        ///Enable FlyCheat mode and press F1 to display global coordinates in game.
        ///
        ///Usage:
        ///LoadCamera = {SOURCE_X_POS}, {SOURCE_Y_POS}, {SOURCE_Z_POS}, {TARGET_X_POS}, {TARGET_Y_POS}, {TARGET_Z_POS}, {ROOM_NUMBER}.
        /// </summary>
        internal static string LoadCamera {
            get {
                return ResourceManager.GetString("LoadCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string LoadSave {
            get {
                return ResourceManager.GetString("LoadSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables a mirror effect.
        ///
        ///Usage:
        ///Mirror = {ROOM_NUMBER}, {ROOM_ORIGIN}.
        /// </summary>
        internal static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The string of text displayed on the &quot;Select Level&quot;, &quot;Load Game&quot; and &quot;Save Game&quot; screens for the level.
        ///The string must be identical to a string in the english.txt file.
        ///
        ///Usage:
        ///Name = {NAME_STRING}.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string PickupCombo {
            get {
                return ResourceManager.GetString("PickupCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables the player to select any level after entering the &quot;New Game&quot; menu.
        ///If disabled, the game won&apos;t open the &quot;New Game&quot; menu, but will directly open the first defined level instead.
        ///
        ///Usage:
        ///PlayAnyLevel = ENABLED / DISABLED.
        /// </summary>
        internal static string PlayAnyLevel {
            get {
                return ResourceManager.GetString("PlayAnyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string PuzzleCombo {
            get {
                return ResourceManager.GetString("PuzzleCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Removes QUEST_ITEM1 from Lara’s inventory at the start of the level.
        ///
        ///Usage:
        ///RemoveAmulet = ENABLED / DISABLED.
        /// </summary>
        internal static string RemoveAmulet {
            get {
                return ResourceManager.GetString("RemoveAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resets the game memory (including FlipEffect info),
        ///removes any information on carried items (puzzles, keys and pickups only),
        ///and reinitialize Lara.
        ///
        ///Useful to free memory space and required if you change the LARA_SKIN object.
        ///Must be used in the level BEFORE the call for the reset
        ///and the parameter must point to the level ID number to be loaded after the reset.
        ///
        ///Usage:
        ///ResetHUB = {LEVEL_ID}.
        /// </summary>
        internal static string ResetHUB {
            get {
                return ResourceManager.GetString("ResetHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Displays an in game cut-scene somewhere in the middle of the level.
        ///Used together with the Cutscene trigger.
        ///The first parameter is the index of the cutscene called by the trigger.
        ///The second parameter is the ID of the cut-scene in the cutseq.pak that will be used.
        ///The executable distributed with the official Level Editor can display these types of cut-scenes
        ///but currently there are no ways to create new ones.
        ///
        ///Usage:
        ///ResidentCut = {TRIGGER_ID}, {CUTSCENE_ID}.
        /// </summary>
        internal static string ResidentCut {
            get {
                return ResourceManager.GetString("ResidentCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shows a timer on the top of the screen, indicating the amount of time spent in the level.
        ///Only works in the second level of the game.
        ///
        ///Usage:
        ///Timer = ENABLED / DISABLED.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specifies if a [Title] section exists.
        ///
        ///Usage:
        ///Title = ENABLED / DISABLED.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enables / Disables the Train level mode.
        ///
        ///Usage:
        ///Train = ENABLED / DISABLED.
        /// </summary>
        internal static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Animates the first textures of your texture set with a scrolling animation.
        ///The parameter sets the speed of the scrolling animation.
        ///Accepted values of speed are in a range between -16 and 16.
        ///
        ///Usage:
        ///UVrotate = {SPEED}.
        /// </summary>
        internal static string UVRotate {
            get {
                return ResourceManager.GetString("UVRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It will disable all weapons, and the holsters will not appear.
        ///Also, Lara’s ponytail will appear as two pigtails instead.
        ///
        ///Usage:
        ///YoungLara = ENABLED / DISABLED.
        /// </summary>
        internal static string YoungLara {
            get {
                return ResourceManager.GetString("YoungLara", resourceCulture);
            }
        }
    }
}
