//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptEditor.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete all bookmarks?.
        /// </summary>
        internal static string ClearBookmarks {
            get {
                return ResourceManager.GetString("ClearBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid game .exe path..
        /// </summary>
        internal static string Error_InvalidGamePath {
            get {
                return ResourceManager.GetString("Error_InvalidGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NG_Center.exe path..
        /// </summary>
        internal static string Error_InvalidNGCenterPath {
            get {
                return ResourceManager.GetString("Error_InvalidNGCenterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the engine type..
        /// </summary>
        internal static string Error_NoEngineType {
            get {
                return ResourceManager.GetString("Error_NoEngineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select your game&apos;s .exe file..
        /// </summary>
        internal static string Error_NoGamePath {
            get {
                return ResourceManager.GetString("Error_NoGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter NG_Center.exe&apos;s path..
        /// </summary>
        internal static string Error_NoNGCenterPath {
            get {
                return ResourceManager.GetString("Error_NoNGCenterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name for your project..
        /// </summary>
        internal static string Error_NoProjectName {
            get {
                return ResourceManager.GetString("Error_NoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SCRIPT.TXT file found in the games&apos;s &quot;Script&quot; directory.
        ///Please make sure your game is installed correctly..
        /// </summary>
        internal static string Error_NoScriptFileFound {
            get {
                return ResourceManager.GetString("Error_NoScriptFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;Script&quot; folder found in game directory.
        ///Please make sure you selected the correct .exe file..
        /// </summary>
        internal static string Error_NoScriptFolderFound {
            get {
                return ResourceManager.GetString("Error_NoScriptFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; project is using the same .exe file as the one you&apos;re currently trying to add.
        ///Please select a different .exe file..
        /// </summary>
        internal static string Error_ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with the same name already exists..
        /// </summary>
        internal static string Error_ProjectNameAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ProjectNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings to default?.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find selected project.
        ///Do you want to delete it from the list?.
        /// </summary>
        internal static string SelectedProjectNotFound {
            get {
                return ResourceManager.GetString("SelectedProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want save changes to {0} ?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
    }
}
