<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Nickelony.LanguageServer.Abstractions">
      <HintPath>..\..\Libs\Nickelony.LanguageServer.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Nickelony.LanguageServer.Lua">
      <HintPath>..\..\Libs\Nickelony.LanguageServer.Lua.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\TombLib.Scripting.Core\TombLib.Scripting.Core.csproj" />
    <ProjectReference Include="..\TombLib.Scripting.UI\TombLib.Scripting.UI.csproj" />
    <ProjectReference Include="..\TombLib.WPF\TombLib.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Configs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Configs\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

</Project>
