namespace TombIDE.ProjectMaster.Splash;

public enum ACCENT
{
	DISABLED = 0,
	ENABLE_GRADIENT = 1,
	ENABLE_TRANSPARENTGRADIENT = 2,
	ENABLE_BLURBEHIND = 3,
	ENABLE_ACRYLICBLURBEHIND = 4,
	INVALID_STATE = 5
}
