<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\Constant.png" />
    <None Remove="Resources\Icons\Directive.png" />
    <None Remove="Resources\Icons\NewCommand.png" />
    <None Remove="Resources\Icons\OldCommand.png" />
    <None Remove="Resources\Icons\Section.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\GlobalPaths.cs">
      <Link>GlobalPaths.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TombLib.Forms\TombLib.Forms.csproj" />
    <ProjectReference Include="..\TombLib.Scripting.UI\TombLib.Scripting.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Configs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Configs\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="Resources\ClassicScript\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Resources\ClassicScript\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreCLR-NCalc" Version="2.2.101" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\Constant.png" />
    <Resource Include="Resources\Icons\Directive.png" />
    <Resource Include="Resources\Icons\NewCommand.png" />
    <Resource Include="Resources\Icons\OldCommand.png" />
    <Resource Include="Resources\Icons\Section.png" />
  </ItemGroup>

</Project>
